import { Image } from "../site-image";
import { SiteFooter, SiteHeader } from "../site-shell";
const leaders=[
  ["Rev. Dr. Kham Suan Hau","Principal","B.A., M.Div., D.Min."],["Rev. Dr. Khup Lian Pau","Academic Dean","B.A., M.Div., D.Min."],["Pastor K Shin Khin Phang","Assistant Academic Dean","B.Th., M.Div., MST"],["Pastor Kham Sian Khai","Dean of Students","B.Th., M.A., M.Div."],["Pastor Mang Kim Sang","Assistant Dean of Students","B.Th., M.A."],["Sayam Cing Lam Man","Campus Pastor","B.Th., M.A."],["Sayama Tin Nay Htay","Girls’ Warden","B.Th., M.Div."],["Saya Pau Sean Sang","Treasurer",""] ,["Sayama Cing Sian Muang","Librarian",""]
];
const faculty=["Rev. Dr. Ram Khuia Ling","Rev. Dr. Luan Khen Khaw Thang","Rev. Dr. Robin Nang Cin Khup","Saya Daniel Thang Cin Pau","Saya JC Cyrene","Rev. Dr. Israel Laphai","Rev. Sain Shwe","Rev. Kam Deih Khen","Saya Thang Za Kim"];
export default function About(){return <main><SiteHeader/><section className="page-hero"><p className="eyebrow">About TSTM</p><h1>A learning community centered on Christ.</h1><p>Since 1999, Trinity School of Theology & Mission has prepared men and women to serve the church and the wider world.</p></section>
  <section className="section about-grid"><div><p className="eyebrow">Our purpose</p><h2>Faith, learning, and mission belong together.</h2><p className="section-lead">We join careful study of Scripture with spiritual growth, Christian character, and practical ministry experience.</p><div className="values">{["Biblical faithfulness","Spiritual formation","Academic excellence","Mission and service"].map((v,i)=><div key={v}><span>0{i+1}</span><b>{v}</b></div>)}</div></div><Image src="/media/leadership.jpg" alt="TSTM president, faculty and student community" width={750} height={600}/></section>
  <section className="leadership-section"><div className="section"><p className="eyebrow">Administration</p><h2>Leaders committed to your formation</h2><div className="people-grid">{leaders.map(([name,role,degree])=><article key={name}><div className="person-initial">{name.split(" ").filter(Boolean).slice(-1)[0][0]}</div><div><h3>{name}</h3><strong>{role}</strong>{degree&&<p>{degree}</p>}</div></article>)}</div></div></section>
  <section className="section"><p className="eyebrow">Teaching faculty</p><h2>Experienced pastors and scholars</h2><div className="faculty-list">{faculty.map((name,i)=><div key={name}><span>{String(i+1).padStart(2,"0")}</span><b>{name}</b></div>)}</div></section><SiteFooter/></main>}
