"use client";

import { useEffect, useState } from "react";

const mm: Record<string, string> = {
  "About":"ကျောင်းအကြောင်း","Programs":"သင်တန်းများ","Admissions":"ကျောင်းဝင်ခွင့်","Contact":"ဆက်သွယ်ရန်","Apply now":"ယခုလျှောက်ထားရန်","Explore":"လေ့လာရန်",
  "Faith · Learning · Mission":"ယုံကြည်ခြင်း · သင်ယူခြင်း · သာသနာပြုခြင်း","Equipping faithful servants for church and world.":"အသင်းတော်နှင့် ကမ္ဘာလောကအတွက် သစ္စာရှိသော အမှုတော်ဆောင်များကို ပြင်ဆင်ပေးခြင်း။","Trinity School of Theology & Mission offers Christ-centered theological education for ministry, leadership, and lifelong service.":"Trinity School of Theology & Mission သည် အမှုတော်ဆောင်ခြင်း၊ ခေါင်းဆောင်မှုနှင့် တစ်သက်တာအစေခံခြင်းအတွက် ခရစ်တော်ဗဟိုပြု ဓမ္မပညာရေးကို ပေးအပ်ပါသည်။","Apply for admission":"ကျောင်းဝင်ခွင့် လျှောက်ထားရန်","Explore programs":"သင်တန်းများ လေ့လာရန်","Est. 1999":"၁၉၉၉ ခုနှစ်တွင် တည်ထောင်သည်","Yangon, Myanmar":"ရန်ကုန်၊ မြန်မာ","Online & campus":"အွန်လိုင်းနှင့် ကျောင်းတွင်း","Flexible study":"ပြောင်းလွယ်ပြင်လွယ် သင်ယူမှု","Admissions open":"ကျောင်းဝင်ခွင့် ဖွင့်လှစ်ထားသည်",
  "Study at TSTM":"TSTM တွင် ပညာသင်ယူပါ","Formed in Scripture. Prepared for ministry.":"ကျမ်းစာအားဖြင့် ပုံသွင်း၍ အမှုတော်အတွက် ပြင်ဆင်သည်။","Choose a program designed to deepen biblical knowledge, strengthen Christian character, and develop practical ministry skills.":"ကျမ်းစာအသိပညာ နက်ရှိုင်းစေခြင်း၊ ခရစ်ယာန်အကျင့်စာရိတ္တ ခိုင်မာစေခြင်းနှင့် လက်တွေ့အမှုတော်ဆောင် ကျွမ်းကျင်မှုများ ဖွံ့ဖြိုးစေမည့် သင်တန်းကို ရွေးချယ်ပါ။","Master of Divinity":"ဓမ္မပညာ မဟာဘွဲ့","Bachelor of Theology":"ဓမ္မပညာ ဘွဲ့","Diploma in Practical Theology":"လက်တွေ့ဓမ္မပညာ ဒီပလိုမာ","View program →":"သင်တန်းကြည့်ရန် →","Our community":"ကျွန်ုပ်တို့၏ အသိုင်းအဝိုင်း","Learning together for faithful service.":"သစ္စာရှိစွာ အစေခံနိုင်ရန် အတူတကွ သင်ယူခြင်း။","Meet our leadership →":"ခေါင်းဆောင်များနှင့် မိတ်ဆက်ရန် →","Latest announcements":"နောက်ဆုံးကြေညာချက်များ","What’s happening at TSTM":"TSTM ၏ လတ်တလောသတင်းများ","All admissions details →":"ကျောင်းဝင်ခွင့် အသေးစိတ် →",
  "Academic programs":"ပညာရေးသင်တန်းများ","Study deeply. Serve faithfully.":"နက်ရှိုင်းစွာ သင်ယူ၍ သစ္စာရှိစွာ အစေခံပါ။","Graduate · Online":"ဘွဲ့လွန် · အွန်လိုင်း","Undergraduate · Four years":"ဘွဲ့ကြို · လေးနှစ်","Online · 66–70 credits":"အွန်လိုင်း · ခရက်ဒစ် ၆၆–၇၀","Four-year course of study":"လေးနှစ်တာ သင်တန်း","Online classes via Zoom":"Zoom ဖြင့် အွန်လိုင်းသင်တန်း","Bachelor certificate and transcript required":"ဘွဲ့လက်မှတ်နှင့် အမှတ်စာရင်း လိုအပ်သည်","Pastoral recommendation required":"သင်းအုပ်ဆရာ၏ ထောက်ခံစာ လိုအပ်သည်","Delivered online through Zoom":"Zoom ဖြင့် အွန်လိုင်းသင်ကြားသည်","Evening class schedule":"ညနေပိုင်း သင်တန်းချိန်","Diploma schedule":"ဒီပလိုမာ သင်တန်းအချိန်ဇယား","Weekly evening classes":"အပတ်စဉ် ညနေပိုင်းသင်တန်းများ","Tuesday":"အင်္ဂါနေ့","Thursday":"ကြာသပတေးနေ့","New Testament Survey":"ဓမ္မသစ်ကျမ်း လေ့လာခြင်း","Spiritual Formation":"ဝိညာဉ်ရေးရာ ပုံသွင်းခြင်း","Foundation of Faith":"ယုံကြည်ခြင်း အခြေခံ","Important dates":"အရေးကြီးရက်များ","Class schedule":"သင်တန်းအချိန်ဇယား","Admission requirements":"ကျောင်းဝင်ခွင့် လိုအပ်ချက်များ","School fees":"ကျောင်းလခများ","Orientation":"မိတ်ဆက်အစီအစဉ်","Classes begin":"သင်တန်းစတင်ခြင်း","Days":"သင်တန်းရက်","Time":"အချိန်","Format":"သင်ကြားမှုပုံစံ","Wednesday & Friday":"ဗုဒ္ဓဟူးနှင့် သောကြာ","Online through Zoom":"Zoom ဖြင့် အွန်လိုင်း","Recommendation from a pastor":"သင်းအုပ်ဆရာ၏ ထောက်ခံစာ","Entrance":"ဝင်ခွင့်ကြေး","Monthly":"လစဉ်ကြေး","Examination":"စာမေးပွဲကြေး",
  "Complete course areas":"သင်ရိုးဘာသာရပ်အပြည့်အစုံ","Old Testament":"ဓမ္မဟောင်းကျမ်း","New Testament":"ဓမ္မသစ်ကျမ်း","Theological Studies":"ဓမ္မပညာ လေ့လာမှု","Christian Life & Faith":"ခရစ်ယာန်အသက်တာနှင့် ယုံကြည်ခြင်း","Mission, ministry & practical subjects":"သာသနာ၊ အမှုတော်နှင့် လက်တွေ့ဘာသာရပ်များ","Language studies: Greek and English":"ဘာသာစကားလေ့လာမှု - ဂရိနှင့် အင်္ဂလိပ်","Complete curriculum overview":"သင်ရိုးညွှန်းတမ်း အပြည့်အစုံ","Biblical subjects":"ကျမ်းစာဘာသာရပ်များ","Theology":"ဓမ္မပညာ","Church & society":"အသင်းတော်နှင့် လူမှုအဖွဲ့အစည်း","Church history":"အသင်းတော်သမိုင်း","Ministry & practical theology":"အမှုတော်နှင့် လက်တွေ့ဓမ္မပညာ","Online course delivered through Zoom":"Zoom ဖြင့် အွန်လိုင်းသင်ကြားသော သင်တန်း",
  "2026–2027 admissions":"၂၀၂၆–၂၀၂၇ ကျောင်းဝင်ခွင့်","Your journey starts here.":"သင်၏ခရီးစဉ် ဤနေရာမှ စတင်ပါသည်။","Admission process":"ကျောင်းဝင်ခွင့် လုပ်ငန်းစဉ်","Five clear steps to join TSTM":"TSTM သို့ ဝင်ရောက်ရန် အဆင့်ငါးဆင့်","Apply":"လျှောက်ထားရန်","Register":"မှတ်ပုံတင်ရန်","Entrance exam":"ဝင်ခွင့်စာမေးပွဲ","Interview":"လူတွေ့စစ်ဆေးခြင်း","Confirm admission":"ဝင်ခွင့်အတည်ပြုခြင်း","Admission schedule":"ကျောင်းဝင်ခွင့် အချိန်ဇယား","New student registration":"ကျောင်းသားသစ် မှတ်ပုံတင်ခြင်း","Entrance examination":"ဝင်ခွင့်စာမေးပွဲ","Orientation program":"မိတ်ဆက်အစီအစဉ်","What you need":"လိုအပ်သည့်အရာများ","Application requirements":"လျှောက်ထားရန် လိုအပ်ချက်များ","Completed application and registration":"လျှောက်လွှာနှင့် မှတ်ပုံတင်ခြင်း ပြည့်စုံရမည်","Previous certificate and academic transcript":"ယခင်ဘွဲ့လက်မှတ်နှင့် အမှတ်စာရင်း","Speak with admissions":"ကျောင်းဝင်ခွင့်ဌာနနှင့် ဆက်သွယ်ရန်","Annual fees":"နှစ်စဉ်ကျောင်းလခ","Clear and transparent costs":"ရှင်းလင်းတိကျသော ကုန်ကျစရိတ်များ","Estimated annual total":"ခန့်မှန်း နှစ်စဉ်စုစုပေါင်း","Registration":"မှတ်ပုံတင်ကြေး","Hostel":"အဆောင်ကြေး","Tuition":"သင်တန်းကြေး","Uniform":"ယူနီဖောင်းကြေး","Library":"စာကြည့်တိုက်ကြေး","Sports":"အားကစားကြေး",
  "About TSTM":"TSTM အကြောင်း","A learning community centered on Christ.":"ခရစ်တော်ကို ဗဟိုပြုသော သင်ယူမှုအသိုင်းအဝိုင်း။","Our purpose":"ကျွန်ုပ်တို့၏ ရည်ရွယ်ချက်","Faith, learning, and mission belong together.":"ယုံကြည်ခြင်း၊ သင်ယူခြင်းနှင့် သာသနာပြုခြင်းသည် အတူတကွ ဖြစ်သည်။","Biblical faithfulness":"ကျမ်းစာအပေါ် သစ္စာရှိခြင်း","Academic excellence":"ပညာရေးထူးချွန်မှု","Mission and service":"သာသနာနှင့် အစေခံခြင်း","Administration":"စီမံခန့်ခွဲမှုအဖွဲ့","Leaders committed to your formation":"သင်၏ဖွံ့ဖြိုးမှုအတွက် အပ်နှံထားသော ခေါင်းဆောင်များ","Teaching faculty":"သင်ကြားရေးဆရာများ","Experienced pastors and scholars":"အတွေ့အကြုံရှိ သင်းအုပ်ဆရာများနှင့် ပညာရှင်များ","Principal":"ကျောင်းအုပ်","Academic Dean":"ပညာရေးဌာနမှူး","Assistant Academic Dean":"လက်ထောက်ပညာရေးဌာနမှူး","Dean of Students":"ကျောင်းသားရေးရာဌာနမှူး","Assistant Dean of Students":"လက်ထောက်ကျောင်းသားရေးရာဌာနမှူး","Campus Pastor":"ကျောင်းဝင်းသင်းအုပ်","Girls’ Warden":"အမျိုးသမီးအဆောင်မှူး","Treasurer":"ဘဏ္ဍာရေးမှူး","Librarian":"စာကြည့်တိုက်မှူး",
  "Contact TSTM":"TSTM သို့ ဆက်သွယ်ရန်","Let’s begin the conversation.":"ယနေ့ပင် ဆက်သွယ်လိုက်ပါ။","Get in touch":"ဆက်သွယ်ရန်","Choose the easiest way to reach us.":"အဆင်ပြေဆုံးနည်းလမ်းဖြင့် ဆက်သွယ်ပါ။","Primary phone":"အဓိကဖုန်း","Additional phone":"အခြားဖုန်း","Main email":"အဓိကအီးမေးလ်","Online course email":"အွန်လိုင်းသင်တန်း အီးမေးလ်","Visit & connect":"လာရောက်ပြီး ဆက်သွယ်ပါ","Arrange a visit":"လာရောက်ရန် စီစဉ်ပါ","Facebook page":"Facebook စာမျက်နှာ","Equipping for faithful service in the church and the world.":"အသင်းတော်နှင့် ကမ္ဘာလောကတွင် သစ္စာရှိစွာ အစေခံရန် ပြင်ဆင်ပေးခြင်း။"
};

const originals = new Map<Text,string>();
function translate(lang:"en"|"mm"){
  document.documentElement.lang=lang==="mm"?"my":"en";
  document.documentElement.dataset.lang=lang;
  const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);
  let node:Text|null;
  while((node=walker.nextNode() as Text|null)){
    const parent=node.parentElement;
    if(!parent||["SCRIPT","STYLE"].includes(parent.tagName)) continue;
    if(!originals.has(node)) originals.set(node,node.data);
    const source=originals.get(node)??node.data;
    if(lang==="en"){node.data=source;continue;}
    const trimmed=source.trim(); const translated=mm[trimmed];
    if(translated) node.data=source.replace(trimmed,translated);
  }
}

export function LanguageToggle(){
  const [lang,setLang]=useState<"en"|"mm">("en");
  useEffect(()=>{const saved=localStorage.getItem("tstm-language")==="mm"?"mm":"en";setLang(saved);requestAnimationFrame(()=>translate(saved));},[]);
  function choose(next:"en"|"mm"){setLang(next);localStorage.setItem("tstm-language",next);translate(next);}
  return <div className="language-toggle" role="group" aria-label="Website language"><button className={lang==="en"?"active":""} onClick={()=>choose("en")} aria-pressed={lang==="en"}>EN</button><button className={lang==="mm"?"active":""} onClick={()=>choose("mm")} aria-pressed={lang==="mm"}>မြန်မာ</button></div>
}
