import { SiteFooter, SiteHeader } from "../site-shell";

const curriculum = [
  {title:"Old Testament",items:["Old Testament Survey","Pentateuch","Historical Books","Poetical Books","Major Prophets","Minor Prophets"]},
  {title:"New Testament",items:["New Testament Survey","Synoptic Gospels","Gospel of John","Book of Acts","Romans & Galatians","1 & 2 Corinthians","Prison Epistles","Pastoral Epistles","General Epistles"]},
  {title:"Theological Studies",items:["Bibliology","Man & Sin","God & Angelology","Ecclesiology","Pneumatology","Christology","Soteriology","Eschatology"]},
  {title:"Christian Life & Faith",items:["Life of Christ","Discipleship","Christian Life","Christian Home","Christian Ethics","Christian Apologetics","Apocalyptic","16 Fundamental Truths","Foundation of Faith","Church History I & II","Cultism"]},
];
const ministrySubjects=["Prayer Ministry","Spiritual Formation","Christian Education I & II","Evangelism","Cross-Cultural Communication","Major World Religions","Introduction to Mission","Homiletics","Hermeneutics","Christian Leadership","Church Planting","Church Growth","Pastoral Care & Counseling","Church Administration","Bible Geography","Biblical Theology of Worship","Youth Ministry","Teaching Methods","Research Method","Study Method","Bible Examination","Computer","Media"];
const diplomaSubjects=[
  {title:"Biblical subjects",items:["Old Testament Survey","New Testament Survey","Biblical Interpretation (Hermeneutics)"]},
  {title:"Theology",items:["Basic Christian Doctrines","Eschatology","Introduction to Biblical Theology","Cultism (False Doctrines)","Pentecostalism"]},
  {title:"Church & society",items:["World Religions","Church & Society"]},
  {title:"Church history",items:["Distinctive Doctrines of Major Christian Denominations","History of Myanmar Christianity"]},
  {title:"Ministry & practical theology",items:["Evangelism","Missions & Church Planting","Biblical Leadership","Church Growth","Theology of Praise & Worship","Stewardship","Effective Teaching Methods","Homiletics (Preaching)","Pastoral Care & Counseling","Biography of Modern Missionaries","Christian Marriage & Family","Life & Ministry of Jesus","Spiritual Formation","Spiritual Gifts","Christian Ethics","Discipleship"]},
];
const diplomaSchedule=[
  {day:"Tuesday",time:"5:30–7:30 PM",course:"New Testament Survey",teacher:"Sya Mang Kim Sang"},
  {day:"Tuesday",time:"7:45–9:45 PM",course:"Distinctive Doctrine of Major Denominations",teacher:"Rev. Chang Bawng"},
  {day:"Thursday",time:"5:30–7:30 PM",course:"Spiritual Formation",teacher:"Rev. Cing Ngaih Lun"},
  {day:"Thursday",time:"7:45–9:45 PM",course:"Foundation of Faith",teacher:"Sya Kshin Khin Phang"},
];

function Program({id,label,title,summary,facts}:{id:string;label:string;title:string;summary:string;facts:string[]}){return <article id={id} className="program-detail"><div><span className="tag">{label}</span><h2>{title}</h2><p>{summary}</p></div><ul className="fact-list">{facts.map(x=><li key={x}>{x}</li>)}</ul></article>}

export default function Programs(){return <main><SiteHeader/><section className="page-hero"><p className="eyebrow">Academic programs</p><h1>Study deeply. Serve faithfully.</h1><p>Every program brings biblical foundations, theological reflection, Christian formation, and practical ministry into one purposeful course of study.</p></section>
  <section className="section program-list">
    <Program id="master" label="Graduate · Online" title="Master of Divinity" summary="A rigorous 96-credit graduate program for pastors, ministry leaders, and students preparing for advanced Christian service." facts={["Online classes via Zoom","Wednesday and Friday · 5:30–9:30 PM","Bachelor certificate and transcript required","Pastoral recommendation required"]}/>
    <Program id="bachelor" label="Undergraduate · Four years" title="Bachelor of Theology" summary="A broad theological education covering Scripture, doctrine, Christian life, mission, ministry practice, language, research, and media." facts={["Four-year course of study","Biblical and theological core","Leadership and ministry formation","English and Greek language studies"]}/>
    <Program id="diploma" label="Online · 66–70 credits" title="Diploma in Practical Theology" summary="A flexible online program designed for church workers and emerging leaders who want a strong foundation for practical ministry." facts={["Delivered online through Zoom","Evening class schedule","Biblical, theological, and ministry subjects","Orientation: June 1 · Classes: June 2"]}/>
  </section>
  <section className="schedule-section"><div className="section"><p className="eyebrow">Diploma schedule</p><h2>Weekly evening classes</h2><div className="schedule-grid">{diplomaSchedule.map((x,i)=><article key={x.course}><span className="schedule-number">0{i+1}</span><div><small>{x.day} · {x.time}</small><h3>{x.course}</h3><p>{x.teacher}</p></div></article>)}</div></div></section>
  <section className="mdiv-details"><div className="section"><div className="section-heading"><div><p className="eyebrow">Master of Divinity · 2026 intake</p><h2>Dates, requirements, and fees</h2></div><span className="intake-pill">96 credit hours · Zoom</span></div><div className="mdiv-grid"><div><h3>Important dates</h3><dl className="compact-list"><div><dt>June 25–July 27</dt><dd>Admissions open</dd></div><div><dt>July 27, 2026</dt><dd>Orientation</dd></div><div><dt>July 29, 2026</dt><dd>Classes begin</dd></div></dl></div><div><h3>Class schedule</h3><dl className="compact-list"><div><dt>Days</dt><dd>Wednesday & Friday</dd></div><div><dt>Time</dt><dd>5:30–9:30 PM</dd></div><div><dt>Format</dt><dd>Online through Zoom</dd></div></dl></div><div><h3>Admission requirements</h3><ul className="plain-checks"><li>Bachelor certificate and transcript</li><li>Recommendation from a pastor</li></ul></div><div><h3>School fees</h3><dl className="compact-list"><div><dt>Entrance</dt><dd>100,000 Ks</dd></div><div><dt>Monthly</dt><dd>50,000 Ks</dd></div><div><dt>Examination</dt><dd>50,000 Ks · 3 trimesters</dd></div></dl></div></div></div></section>
  <section className="curriculum"><div className="section"><p className="eyebrow">Bachelor of Theology</p><h2>Complete course areas</h2><div className="curriculum-grid">{curriculum.map(g=><div key={g.title}><h3>{g.title}</h3><ul>{g.items.map(x=><li key={x}>{x}</li>)}</ul></div>)}</div><div className="ministry-list"><h3>Mission, ministry & practical subjects</h3><div>{ministrySubjects.map(x=><span key={x}>{x}</span>)}</div><p>Language studies: Greek and English</p></div></div></section>
  <section className="section"><p className="eyebrow">Diploma in Practical Theology</p><h2>Complete curriculum overview</h2><div className="diploma-subject-grid">{diplomaSubjects.map(g=><article key={g.title}><h3>{g.title}</h3><ol>{g.items.map(x=><li key={x}>{x}</li>)}</ol></article>)}</div><div className="credit-callout"><strong>66–70 credits</strong><span>Online course delivered through Zoom</span></div></section><SiteFooter/></main>}
