import Image from "next/image";
import { SiteFooter, SiteHeader } from "../site-shell";

const groups = [
  ["Biblical Studies", "Old & New Testament Survey", "Pentateuch", "Gospels and Acts", "Romans and Galatians", "Biblical Interpretation"],
  ["Theological Studies", "Bibliology", "Christology", "Pneumatology", "Soteriology", "Eschatology"],
  ["Ministry & Mission", "Evangelism", "Church Planting", "Christian Leadership", "Pastoral Care", "Spiritual Formation"],
];

export default function Programs() { return <main><SiteHeader/><section className="page-hero"><p className="eyebrow">Academic programs</p><h1>Study deeply. Serve faithfully.</h1><p>Programs combine biblical foundations, theological study, Christian formation, and practical ministry.</p></section><section className="section program-list"><article id="master"><div><span className="tag">Graduate program</span><h2>Master of Divinity</h2><p>A 96-credit online program for advanced biblical, theological, and ministry preparation.</p><ul><li>Online classes via Zoom</li><li>Wednesday and Friday evenings</li><li>Bachelor certificate and transcript required</li></ul></div><Image src="/media/master-divinity.jpg" alt="Master of Divinity program" width={500} height={750}/></article><article id="bachelor"><div><span className="tag">Undergraduate program</span><h2>Bachelor of Theology</h2><p>A four-year course of study with comprehensive preparation in Bible, theology, ministry, mission, and Christian life.</p></div><Image src="/media/course-subjects.jpg" alt="Bachelor of Theology course subjects" width={700} height={540}/></article><article id="diploma"><div><span className="tag">Online program</span><h2>Diploma in Practical Theology</h2><p>A flexible 66–70 credit program covering biblical subjects, theology, church history, society, and practical ministry.</p></div><Image src="/media/diploma-program.jpg" alt="Diploma in Practical Theology details" width={500} height={700}/></article></section><section className="curriculum"><div className="section"><p className="eyebrow">Course areas</p><h2>A whole-person theological education</h2><div className="curriculum-grid">{groups.map(g=><div key={g[0]}><h3>{g[0]}</h3>{g.slice(1).map(x=><p key={x}>{x}</p>)}</div>)}</div></div></section><SiteFooter/></main> }
